name: Docker build image

on:
  push:
    branches: master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} 
      - name: "[Mirakurun] Push to GitHub Container Registry"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: data/mirakurun
          file: data/mirakurun/Dockerfile
          tags: ghcr.io/sobadon/mirakurun:custom-latest
      - name: "[EPGStation] Push to GitHub Container Registry"
        uses: docker/build-push-action@v2
        with:
          push: true
          context: data/epgstation
          file: data/epgstation/Dockerfile
          tags: ghcr.io/sobadon/epgstation:custom-latest

